### ISSUE TITLE
cannot read property length

### ISSUE THREAD

**Issue by ciavez** [justinhulin/homebridge-newfoscam#1]
hi,
I'm sure I'm doing things right but I've got this error 

 [NewFoscam] Initializing platform accessory 'Foscam KITCHA'...
(node:2020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Accessory.configureCameraSource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:544:40)
    at PlatformAccessory.configureCameraSource (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:132:41)
    at FoscamPlatform.configureCamera (/usr/local/lib/node_modules/homebridge-newfoscam/index.js:168:16)
    at /usr/local/lib/node_modules/homebridge-newfoscam/index.js:55:18
    at /usr/local/lib/node_modules/homebridge-newfoscam/index.js:145:7
(Use `node --trace-warnings ...` to show where the warning was created)

and this is the json

{
            "platform": "NewFoscam",
            "cameras": [
                {
                    "username": "TTTT",
                    "password": "XXXX",
                    "host": "YYYY",
                    "port": 88,
                    "stay": 13,
                    "away": 15,
                    "night": 14,
                    "armPreset": "Start",
                    "disarmPreset": "LeftMost",
                    "sensitivity": 2,
                    "triggerInterval": 5,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://XXXXX@YYYY:88/videoMain",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30
                    }
                }
            ]

**Comment by ciavez** [comment]
fixed by editing index.js in this way



// Method to configure camera info for HomeKit
FoscamPlatform.prototype.configureCamera = function (mac) {
  var self = this;
  var thisCamera = this.cameraInfo[mac];
  // var thisFoscamAPI = this.foscamAPI
  var thisapi = this.api;
  var name = "Foscam " + thisCamera.name;
  var uuid = UUIDGen.generate(mac);

  this.log("Initializing platform accessory '" + name + "'...");

  // Setup for FoscamAccessory
  var videoProcessor = self.config.videoProcessor || 'ffmpeg';
  var cameraSource = new StreamingDelegate(self.log, thisCamera, thisapi, hap, videoProcessor);
  // let cameraSource = new StreamingDelegate(log: self.log, cameraConfig: thisCamera, api: thisFoscamAPI, hap: hap, videoProcessor: thisvideoProcessor);
  var newAccessory = new Accessory(name, uuid, hap.Accessory.Categories.CAMERA);
  
  newAccessory.configureController(cameraSource.controller);
  //  newAccessory.configureCameraSource(cameraSource);

**Comment by justinhulin** [comment]
Hey Ciavez,
I am not a coder and honestly I was just trying to find a way to make this older Foscam plugin work so I could use the motion and all that but never could get the stream to work. Didn’t won’t to use homebridge camera ffmpeg cause that didn’t allow for Foscam api. Thanks for letting me know this I will tinker with it later
